//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentID { get; set; }
        public int OrderNumber { get; set; }
        public int ReceiptNumber { get; set; }
        public decimal PaymentAmount { get; set; }
    
        public virtual MoneyReceipts MoneyReceipts { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
